version: '3.5'

services:
  twofaqr:
    container_name: twofaqr
    image: nginx:alpine
    labels:
      - "traefik.enable=false"  
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - "8083:80"
    security_opt:
      - seccomp:unconfined

